---
title: "Chapter 2 Applied Exercises"
author: "Cool Beans Programming"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading libraries and data

```{r warning=FALSE, message=FALSE}
library(ISLR2)
```



```{r read_college}
college <- read.csv("https://www.statlearning.com/s/College.csv")
rownames(college) <- college[, 1]
View(college)
```

## Exploring the data

```{r view_college}
college <- college[, -1]
head(college)
```

```{r summary_college}
summary(college)
```
```{r college_pairs}
# convert Private to factor variable 
college$Private <-as.factor(college$Private)
pairs(college[,1:5])
```


## Graphing the data
```{r college_outstate_private_plot}
boxplot(college$Outstate ~ college$Private, xlab= "Private", ylab="Outstate", 
        main="Out of State Tuition vs Private")
```
```{r create_elite}
Elite <-rep("No", nrow(college))
Elite[college$Top10perc > 50] <-"Yes"
Elite <-as.factor(Elite)
college <-data.frame(college,Elite)
```

```{r elite_summary}
summary(college)
``` 

```{r elite_boxplots}
boxplot(college$Outstate ~ college$Elite, xlab="Elite",ylab="Outstate", 
        main="Out of State Tuition vs Elite")
```
```{r college_hist}
par(mfrow=c(2,2))
hist(college$Apps, xlab="Apps Received", ylab="", main="Dist. of Applications Received")
hist(college$Accept, xlab="Apps Accepted", ylab="", main="Dist. of Applications Accepted")
hist(college$Room.Board, xlab="Room and Board Cost", ylab="", main="Dist. of Room & Board Costs")
hist(college$Books, xlab="Estimated Book Cost", ylab="", main="Dist. of Textbook Costs")
```

